### ISSUE TITLE
StumpWM config not found

### ISSUE THREAD

**Issue by markgdawson** [jamesmccabe/dotfiles#1]
The link to the stumpwm config you mention isn't found. You referenced this in a stumpwm font awesome issue.

I would very much like to see the config to see how you got font awesome working with the mode line. Is this possible?

**Comment by jamesmccabe** [comment]
@M4rkD I haven't used Stump in a while. but just getting back to it.
I quickly uploaded my old Stumpwm config at:
[https://github.com/jamesmccabe/stumpwm-config](https://github.com/jamesmccabe/stumpwm-config)

If you have questions on getting it working, you can let me know. James.

**Comment by markgdawson** [comment]
@jamesmccabe, thanks for your response. I managed to get the Awesome font thing working in the end. Turns out it was an issue outside of StumpWM.

But thanks for sharing the config. I learnt a thing or two from it anyway, definitely a few little settings I didn't know about that I'll borrow.
